### PR TITLE
Resolve #2

### LINKED ISSUE #2: Support multi-value variables
in [datasource.ts](https://github.com/andrewchambers/grafana-rrd-datasource/blob/675e98283ea0b89b735ff2c296f1d5f92acc6886/src/datasource.ts#L11), on line 11,  adding `scopedVars` to the getTemplateSrv() call, like:
`query.xport = getTemplateSrv().replace(query.xport, scopedVars);`
allows the [Repeat by variable](https://grafana.com/blog/2020/06/09/learn-grafana-how-to-automatically-repeat-rows-and-panels-in-dynamic-dashboards/) feature to work. Without this, the replace() call will put EVERY value of the variable into the xport string.

### PR DESCRIPTION
**Pull request by cuuush**
Resolves #2 Support multi-value variables
Also remove the yarn.lock, which prevented me from installing non-deprecated packages.

### CODE REVIEW

**Comment by andrewchambers** [comment]
Hi, looks good, I think we should still commit an updated yarn.lock file so people can get a tested version. I don't mind doing that later.

**Comment by cuuush** [comment]
Sorry for clutter, I'm going to maintain a fork until #2 gets resolved, unless you're ok with my change bumping version to v1.0.1. Also, thanks so much for creating this!

**Comment by andrewchambers** [comment]
I'm ok with it, sorry I thought I had already merged your changes.

**Comment by andrewchambers** [comment]
I'm ok with it, sorry I thought I had already merged your changes.

**Comment by cuuush** [comment]
sure, not sure if anything else needs to be done for release.

**Comment by andrewchambers** [comment]
Not much, I just need to test some things myself, though I'm currently a bit busy.

**Pull request merged**
